version: "3.7"

x-base_go_service: &base_go_service
  image: golang
  volumes:
    - ${PWD}/../../:/go/src/ws
  working_dir: /go/src/ws

services:
  constructserver:
    <<: *base_go_service
    command: go run ./example/gateway/constructserver/main.go

  optionsserver:
    <<: *base_go_service
    command: go run ./example/gateway/optionsserver/main.go

  gateway:
    <<: *base_go_service
    command: go run ./cmd/gateway/main.go --cfg ./example/gateway/config.json
    ports:
    - 8080:8080
